### ISSUE TITLE
Error installing via npm

### ISSUE THREAD

**Issue by bgsavage** [dennis-b/NG2TableView#3]
`npm i NG2TableView --save` fails
npm version: 4.2.0

Erorr log below:
7179 error Darwin 16.5.0
7180 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "NG2TableView" "--save"
7181 error node v7.7.3
7182 error npm  v4.2.0
7183 error code ELIFECYCLE
7184 error errno 1
7185 error NG2TableView@1.0.7 postinstall: `npm run typings -- install`
7185 error Exit status 1
7186 error Failed at the NG2TableView@1.0.7 postinstall script 'npm run typings -- install'.
7186 error Make sure you have the latest version of node.js and npm installed.
7186 error If you do, this is most likely a problem with the NG2TableView package,
7186 error not with npm itself.
7186 error Tell the author that this fails on your system:
7186 error     npm run typings -- install
7186 error You can get information on how to open an issue for this project with:
7186 error     npm bugs NG2TableView
7186 error Or if that isn't available, you can get their info via:
7186 error     npm owner ls NG2TableView
7186 error There is likely additional logging output above.

**Comment by dennis-b** [comment]
@bgsavage thank you, new version published
