### ISSUE TITLE
Demo not up to date with current version

### ISSUE THREAD

**Issue by e11en** [dennis-b/NG2TableView#4]
Hi just wanted to let you know that the demo is not up to date with the current code.

example:
`import {TableView} from "ng2-table-view";` doesn't work but `import {TableView} from 'NG2TableView';` does.

Maybe I need to dive in it a bit more but I couldn't get it to work in my project.

**Comment by dennis-b** [comment]
thank you @e11en,
i have updated readme for correct imports.
the demo is not separate project , its part of NG2TableView, so all imports in demo is relative .
for running the demo just run:

1 - `git clone https://github.com/dennis-b/NG2TableView.git`
2 - `cd NG2TableView`
3 - `npm i`
4 - `npm start`
5 - navigate to http://localhost:8080/

Best regards 
Dennis
