### ISSUE TITLE
Do this support angular 4 ?

### ISSUE THREAD

**Issue by ashwinpatiljumia** [dennis-b/NG2TableView#5]
Hello,
Does this lib supports angular 4 ?
I am having some trouble while running this with Angular 4.

Thanks for answer.

Regards,
Ashwin PATIL

**Comment by dennis-b** [comment]
Hi Ashwin PATIL

i have added ng 4 support. please tell if u still have any problem.
also i updated the demo, so u can just run:
npm i
ng serve (i using angular cli for the demo)

Best Regards
Dennis
